/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    projects: Project;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('nl' | 'en') | ('nl' | 'en')[];
  globals: {
    header: Header;
    footer: Footer;
    integrations: Integration;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
  };
  locale: 'nl' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive alt text. Auto-filled from filename if blank.
   */
  alt: string;
  /**
   * Optional caption shown beneath the image.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path. Use 'home' for the homepage. Same across locales.
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Compose this page by stacking blocks.
   */
  layout?:
    | (
        | {
            /**
             * Show or hide this section.
             */
            enabled?: boolean | null;
            /**
             * Full-bleed background image. Falls back to a default if empty.
             */
            image?: (number | null) | Media;
            /**
             * Tagline shown over the image, e.g. 'Interior, Craft & Design'.
             */
            caption?: string | null;
            /**
             * Show the Rift starburst above the caption.
             */
            showStarburst?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Show or hide this section.
             */
            enabled?: boolean | null;
            /**
             * Optional heading shown above the columns.
             */
            heading?: string | null;
            /**
             * Body copy. Each entry renders as its own paragraph.
             */
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            image?: (number | null) | Media;
            imagePosition?: ('right' | 'left') | null;
            /**
             * How wide the text column is relative to the image.
             */
            ratio?: ('third' | 'quarter') | null;
            /**
             * How the text column aligns vertically against the image on desktop.
             */
            textVerticalAlign?: ('top' | 'center' | 'bottom') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textWithImage';
          }
        | {
            /**
             * Show or hide this section.
             */
            enabled?: boolean | null;
            /**
             * Paragraph shown above the quote.
             */
            leadingText?: string | null;
            /**
             * Short quote, e.g. 'Where ideas take shape in timeless interiors'.
             */
            quote?: string | null;
            /**
             * Label shown before the quote, e.g. 'RIFT'.
             */
            attributionLabel?: string | null;
            /**
             * Always shown.
             */
            imageOne?: (number | null) | Media;
            /**
             * Hidden on mobile, shown on tablet+.
             */
            imageTwo?: (number | null) | Media;
            quotePosition?: ('right' | 'left') | null;
            /**
             * How the quote column aligns vertically against the images on desktop.
             */
            textVerticalAlign?: ('top' | 'center' | 'bottom') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoImagesQuote';
          }
        | {
            /**
             * Show or hide this step.
             */
            enabled?: boolean | null;
            /**
             * Optional prefix shown before the title, e.g. '1.'
             */
            stepNumber?: string | null;
            title: string;
            description: string;
            imagePosition?: ('right' | 'left') | null;
            /**
             * Always shown.
             */
            imageOne?: (number | null) | Media;
            /**
             * Optional second image. When set, the section uses the double-image layout.
             */
            imageTwo?: (number | null) | Media;
            /**
             * How the text column aligns vertically against the image(s) on desktop.
             */
            textVerticalAlign?: ('top' | 'center' | 'bottom') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'processStep';
          }
        | {
            /**
             * Show or hide this section.
             */
            enabled?: boolean | null;
            heading?: string | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
      )[]
    | null;
  meta: {
    title: string;
    description: string;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * URL path under /projects/. Same across locales.
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Full-bleed hero image at the top of the project page. Upload via admin.
   */
  heroImage?: (number | null) | Media;
  /**
   * Image shown on the projects overview grid. Falls back to heroImage if empty.
   */
  thumbnail?: (number | null) | Media;
  /**
   * Short paragraph below the hero.
   */
  intro: string;
  /**
   * Body of the project page, composed of blocks.
   */
  layout?:
    | (
        | {
            /**
             * Show or hide this section.
             */
            enabled?: boolean | null;
            /**
             * Optional heading shown above the columns.
             */
            heading?: string | null;
            /**
             * Body copy. Each entry renders as its own paragraph.
             */
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            image?: (number | null) | Media;
            imagePosition?: ('right' | 'left') | null;
            /**
             * How wide the text column is relative to the image.
             */
            ratio?: ('third' | 'quarter') | null;
            /**
             * How the text column aligns vertically against the image on desktop.
             */
            textVerticalAlign?: ('top' | 'center' | 'bottom') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textWithImage';
          }
        | {
            /**
             * Show or hide this section.
             */
            enabled?: boolean | null;
            /**
             * Hidden on mobile, shown on tablet+.
             */
            imageOne?: (number | null) | Media;
            /**
             * Always shown.
             */
            imageTwo?: (number | null) | Media;
            /**
             * Body copy that wraps around the images on desktop.
             */
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'floatedImagePair';
          }
        | {
            /**
             * Show or hide this section.
             */
            enabled?: boolean | null;
            heading?: string | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
      )[]
    | null;
  meta: {
    title: string;
    description: string;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              enabled?: T;
              image?: T;
              caption?: T;
              showStarburst?: T;
              id?: T;
              blockName?: T;
            };
        textWithImage?:
          | T
          | {
              enabled?: T;
              heading?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              image?: T;
              imagePosition?: T;
              ratio?: T;
              textVerticalAlign?: T;
              id?: T;
              blockName?: T;
            };
        twoImagesQuote?:
          | T
          | {
              enabled?: T;
              leadingText?: T;
              quote?: T;
              attributionLabel?: T;
              imageOne?: T;
              imageTwo?: T;
              quotePosition?: T;
              textVerticalAlign?: T;
              id?: T;
              blockName?: T;
            };
        processStep?:
          | T
          | {
              enabled?: T;
              stepNumber?: T;
              title?: T;
              description?: T;
              imagePosition?: T;
              imageOne?: T;
              imageTwo?: T;
              textVerticalAlign?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              enabled?: T;
              heading?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  heroImage?: T;
  thumbnail?: T;
  intro?: T;
  layout?:
    | T
    | {
        textWithImage?:
          | T
          | {
              enabled?: T;
              heading?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              image?: T;
              imagePosition?: T;
              ratio?: T;
              textVerticalAlign?: T;
              id?: T;
              blockName?: T;
            };
        floatedImagePair?:
          | T
          | {
              enabled?: T;
              imageOne?: T;
              imageTwo?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              enabled?: T;
              heading?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Top-level navigation links.
   */
  navItems?:
    | {
        label: string;
        /**
         * Path without locale prefix, e.g. /projects. The current locale is added automatically.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Short line shown next to the starburst, e.g. 'Get in touch...'
   */
  tagline: string;
  /**
   * Contact email shown in the footer.
   */
  email?: string | null;
  links?:
    | {
        label: string;
        href: string;
        /**
         * Open in a new tab.
         */
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  googleAnalytics?: {
    enabled?: boolean | null;
    /**
     * GA4 ID (e.g. G-XXXXXXX)
     */
    measurementId?: string | null;
  };
  metaPixel?: {
    enabled?: boolean | null;
    pixelId?: string | null;
  };
  /**
   * Paste arbitrary script snippets (e.g. Hotjar). Use sparingly.
   */
  customScripts?:
    | {
        /**
         * Internal label for editors.
         */
        label?: string | null;
        placement?: ('head' | 'body') | null;
        script: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  email?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  googleAnalytics?:
    | T
    | {
        enabled?: T;
        measurementId?: T;
      };
  metaPixel?:
    | T
    | {
        enabled?: T;
        pixelId?: T;
      };
  customScripts?:
    | T
    | {
        label?: T;
        placement?: T;
        script?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}